[uwsgi]
chdir = /app/python
module = gis_website.wsgi:application
master = true
processes = 4
socket = /tmp/uwsgi.sock
chmod-socket = 666
vacuum = true
die-on-term = true
enable-threads = true
# Necessario per Django
env = DJANGO_SETTINGS_MODULE=gis_website.settings